### ISSUE TITLE
Could you kindly explain or share a resource (code or literature) that you used for computing shading, attached shadows, and the specular components from the ground truth lightings and surface normals?

### ISSUE THREAD

**Issue by ashisht96** [guanyingc/UPS-GCNet#1]

**Comment by guanyingc** [comment]
Hi, you can find the code for computing these three components in 

https://github.com/guanyingc/UPS-GCNet/blob/8bb7b5dc89ec21404deefb91a1f06b07644103c4/datasets/pms_transforms.py#L80-L110

You can find the formula in the paper.

**Comment by ashisht96** [comment]
Thanks!
