### ISSUE TITLE
Download problem: bash scripts/download_pretrained_models.sh

### ISSUE THREAD

**Issue by Banhalmi** [guanyingc/UPS-GCNet#10]
HTTP request sent, awaiting response... 500 Internal Server Error
2022-04-20 11:19:32 ERROR 500: Internal Server Error.

**Comment by guanyingc** [comment]
Hi, please download the models from google drive if this script does not work 
![image](https://user-images.githubusercontent.com/8651158/164233781-ba6cb279-d622-4da3-a004-d1adb4ade97a.png)
