### ISSUE TITLE
The test as you provided reported an error

### ISSUE THREAD

**Issue by yangyuze1** [guanyingc/UPS-GCNet#12]
![image](https://user-images.githubusercontent.com/39641399/191047820-b947948c-4170-4258-bc54-fb70b1486703.png)

The test as you provided reported an error

![image](https://user-images.githubusercontent.com/39641399/191048161-f68f1369-5f1b-413e-9206-9031fb80ec1a.png)

The question is from here, how to change

**Comment by guanyingc** [comment]
Sorry for missing this issue. This problem might be caused by the difference in paths between the Unix and Windows systems, which is similar to https://github.com/guanyingc/DeepHDRVideo/issues/21.
