### ISSUE TITLE
How to use custom dataset?

### ISSUE THREAD

**Issue by xpirad** [guanyingc/UPS-GCNet#2]
Hello, sorry for disturbing. I'm wondering if this project supports custom dataset as SDPS-Net  does?

[ups_Custom_Dataset.zip](https://github.com/guanyingc/UPS-GCNet/files/5377932/ups_Custom_Dataset.zip)

I tried writing an Ups_custom_dataset class myself. But the output is kinda weird and i don't know what goes wrong. Could you help me out please?..

![image](https://user-images.githubusercontent.com/24430064/95984624-0c397300-0e56-11eb-9e50-cd42affb156b.png)
This is the output, which obviously isn't quite right..

![image](https://user-images.githubusercontent.com/24430064/95984662-1c515280-0e56-11eb-94e4-7bceb9903b20.png)
And this is the groundtruth.

Any help would be appreciated, thank you!!

**Comment by guanyingc** [comment]
Hi, sorry for the late reply. I am very busy recently and have no time to looking into it in these few days. I am so sorry about it.

I think this code can support ups_Custom_Dataset.py, but may need some modifications. I have provided dataloaders for different datasets, you may have a look on those examples.

Have you try SDPS-Net code on your dataset? UPS-GCNet should be able to perform better. However, if SDPS-Net generates similar results, our method may fail.

**Comment by xpirad** [comment]
Guanying thanks for your reply! 
Yes i have tried SDPS-Net and it works well on our custom dataset. 
However i can't get it to work on GCNet. I made some modification so that it would run on GCNet, but the results are really weird.
Could you shed some light on me please TAT?

**Comment by xpirad** [comment]
I solved it. Was using the wrong command. Sorry for the trouble!

**Comment by xpirad** [comment]
@guanyingc BTW, can i ask if there's any pre-processing required if i want to use my own dataset? Thanks!!!

**Comment by guanyingc** [comment]
Hi, what do you mean by saying "pre-processing"?

**Comment by xpirad** [comment]
Hello guanying, i was saying if i need to save it in a specific format, like the images in the DiLiGenT Dataset are 16 bit linear images.
Do i need to keep my dataset in that way as well? 
Thanks !!

**Comment by guanyingc** [comment]
Hi, 
You have to make sure the input images are linear. However, whether it is 16 bit or 8 bit is not very important. In fact, the DiLiGenT dataloader read the images in 8 bit format (imread in imageio only support 8 bit png).

Please refer to https://github.com/guanyingc/SDPS-Net/issues/9 for more information.

**Comment by xpirad** [comment]
Thanks guanying. Can you enlighten me on how to save image in linear format?
I searched for "convert image into linear python" or "linear image python" but i can't seem to find a tutorial to do it. 
Am i using the right keyword here? Thanks!!!
Sorry for the dumb question!!

**Comment by guanyingc** [comment]
Hi, please kindly refer to the DiLiGenT paper for how to capture the dataset by yourself. 

<img width="568" alt="Screen Shot 2020-10-23 at 2 30 24 PM" src="https://user-images.githubusercontent.com/8651158/96964139-847df380-153c-11eb-848e-6862c8cfb61c.png">

**Comment by xpirad** [comment]
Thank you guanying!! I see, thanks!!!
