### ISSUE TITLE
 different material maps to generate a synthetic dataset

### ISSUE THREAD

**Issue by HADESforCode** [guanyingc/UPS-GCNet#4]
Could you provide me with the synthetic data set of different material maps used in your paper？thanks a lot

**Comment by guanyingc** [comment]
Hi, in fact, we generated patterns (e.g., checkerboard) to blend two images rendered under different materials but under the same light direction.

For example, we have shared objects rendered under 100 MERF BRDFS. In each BRDF, the lighting distributions are the same. You can pick two BRDFs, and use a checkerboard pattern to blend two images rendered under the same light direction.

**Comment by HADESforCode** [comment]
Thanks！！！！！
